URL_DIAMOND="http://192.168.150.10:5462/request"
SAVE_DIRECTORY="Z:/"
SHARE_DIRECTORY_IN_STORAGE="D:/Share/NR-301/"
URL_DIAMOND="http://localhost:5462/request"
SAVE_DIRECTORY="C:/Users/yutay/Documents/test/"
SHARE_DIRECTORY_IN_STORAGE="C:/Test/Share/"
