# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Project\Data_Memo_Transfer\forms\FormSubWidgetExperimentInformation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LAB_Title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LAB_Title.setFont(font)
        self.LAB_Title.setObjectName("LAB_Title")
        self.verticalLayout.addWidget(self.LAB_Title)
        self.LE_Title = QtWidgets.QLineEdit(Form)
        self.LE_Title.setEnabled(True)
        self.LE_Title.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LE_Title.setFont(font)
        self.LE_Title.setReadOnly(False)
        self.LE_Title.setObjectName("LE_Title")
        self.verticalLayout.addWidget(self.LE_Title)
        self.LAB_Title_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LAB_Title_2.setFont(font)
        self.LAB_Title_2.setObjectName("LAB_Title_2")
        self.verticalLayout.addWidget(self.LAB_Title_2)
        self.TE_Experiment_Comment = QtWidgets.QPlainTextEdit(Form)
        self.TE_Experiment_Comment.setEnabled(True)
        self.TE_Experiment_Comment.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TE_Experiment_Comment.setFont(font)
        self.TE_Experiment_Comment.setObjectName("TE_Experiment_Comment")
        self.verticalLayout.addWidget(self.TE_Experiment_Comment)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LAB_Title.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:700;\">*Experiment Title</span></p></body></html>"))
        self.LAB_Title_2.setText(_translate("Form", "Experiment Comment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
