# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Project\Data_Memo_Transfer\forms\FormDialogLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 171)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LAB_Usage_ID = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LAB_Usage_ID.setFont(font)
        self.LAB_Usage_ID.setObjectName("LAB_Usage_ID")
        self.verticalLayout.addWidget(self.LAB_Usage_ID)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LAB_Title = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LAB_Title.setFont(font)
        self.LAB_Title.setObjectName("LAB_Title")
        self.horizontalLayout.addWidget(self.LAB_Title)
        self.LE_Experiment_ID = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Experiment_ID.setFont(font)
        self.LE_Experiment_ID.setText("")
        self.LE_Experiment_ID.setObjectName("LE_Experiment_ID")
        self.horizontalLayout.addWidget(self.LE_Experiment_ID)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LAB_Title_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LAB_Title_2.setFont(font)
        self.LAB_Title_2.setObjectName("LAB_Title_2")
        self.horizontalLayout_2.addWidget(self.LAB_Title_2)
        self.LE_Password = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Password.setFont(font)
        self.LE_Password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.LE_Password.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.LE_Password.setText("")
        self.LE_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LE_Password.setObjectName("LE_Password")
        self.horizontalLayout_2.addWidget(self.LE_Password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.PB_Log_In = QtWidgets.QPushButton(Dialog)
        self.PB_Log_In.setObjectName("PB_Log_In")
        self.horizontalLayout_3.addWidget(self.PB_Log_In)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LAB_Usage_ID_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LAB_Usage_ID_2.setFont(font)
        self.LAB_Usage_ID_2.setObjectName("LAB_Usage_ID_2")
        self.horizontalLayout_4.addWidget(self.LAB_Usage_ID_2)
        self.PB_Reset_Password = QtWidgets.QPushButton(Dialog)
        self.PB_Reset_Password.setObjectName("PB_Reset_Password")
        self.horizontalLayout_4.addWidget(self.PB_Reset_Password)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LAB_Usage_ID.setText(_translate("Dialog", "Input your Experiment ID and Password"))
        self.LAB_Title.setText(_translate("Dialog", "Experiment ID"))
        self.LAB_Title_2.setText(_translate("Dialog", "Password"))
        self.PB_Log_In.setText(_translate("Dialog", "log in"))
        self.LAB_Usage_ID_2.setText(_translate("Dialog", "If you use for the first time or forget your password"))
        self.PB_Reset_Password.setText(_translate("Dialog", "Reset password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
