# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Project\Data_Memo_Transfer\forms\FormSendOneTimePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 175)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LAB_Usage_ID = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LAB_Usage_ID.setFont(font)
        self.LAB_Usage_ID.setObjectName("LAB_Usage_ID")
        self.verticalLayout.addWidget(self.LAB_Usage_ID)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LAB_Title = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LAB_Title.setFont(font)
        self.LAB_Title.setObjectName("LAB_Title")
        self.horizontalLayout.addWidget(self.LAB_Title)
        self.LE_Experiment_ID = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Experiment_ID.setFont(font)
        self.LE_Experiment_ID.setText("")
        self.LE_Experiment_ID.setObjectName("LE_Experiment_ID")
        self.horizontalLayout.addWidget(self.LE_Experiment_ID)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.GB_Send_To = QtWidgets.QGroupBox(Dialog)
        self.GB_Send_To.setObjectName("GB_Send_To")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GB_Send_To)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RB_Send_To_Self = QtWidgets.QRadioButton(self.GB_Send_To)
        self.RB_Send_To_Self.setChecked(True)
        self.RB_Send_To_Self.setObjectName("RB_Send_To_Self")
        self.horizontalLayout_2.addWidget(self.RB_Send_To_Self)
        self.RB_Send_To_Supervisor = QtWidgets.QRadioButton(self.GB_Send_To)
        self.RB_Send_To_Supervisor.setChecked(False)
        self.RB_Send_To_Supervisor.setObjectName("RB_Send_To_Supervisor")
        self.horizontalLayout_2.addWidget(self.RB_Send_To_Supervisor)
        self.verticalLayout.addWidget(self.GB_Send_To)
        self.PB_Send_One_Time_Password = QtWidgets.QPushButton(Dialog)
        self.PB_Send_One_Time_Password.setObjectName("PB_Send_One_Time_Password")
        self.verticalLayout.addWidget(self.PB_Send_One_Time_Password)
        self.PB_Cancel = QtWidgets.QPushButton(Dialog)
        self.PB_Cancel.setObjectName("PB_Cancel")
        self.verticalLayout.addWidget(self.PB_Cancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LAB_Usage_ID.setText(_translate("Dialog", "Input your Experiment ID"))
        self.LAB_Title.setText(_translate("Dialog", "Experiment ID"))
        self.GB_Send_To.setTitle(_translate("Dialog", "Send to ..."))
        self.RB_Send_To_Self.setText(_translate("Dialog", "Self"))
        self.RB_Send_To_Supervisor.setText(_translate("Dialog", "Supervisor"))
        self.PB_Send_One_Time_Password.setText(_translate("Dialog", "Send One Time Password To Registered e-mail address"))
        self.PB_Cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
