# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/Widget_Sample_Information.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LAB_Sample_Name = QtWidgets.QLabel(Form)
        self.LAB_Sample_Name.setObjectName("LAB_Sample_Name")
        self.verticalLayout.addWidget(self.LAB_Sample_Name)
        self.LE_Sample_Name = QtWidgets.QLineEdit(Form)
        self.LE_Sample_Name.setObjectName("LE_Sample_Name")
        self.verticalLayout.addWidget(self.LE_Sample_Name)
        self.LAB_Sample_ID_2 = QtWidgets.QLabel(Form)
        self.LAB_Sample_ID_2.setObjectName("LAB_Sample_ID_2")
        self.verticalLayout.addWidget(self.LAB_Sample_ID_2)
        self.LE_Sample_ID = QtWidgets.QLineEdit(Form)
        self.LE_Sample_ID.setObjectName("LE_Sample_ID")
        self.verticalLayout.addWidget(self.LE_Sample_ID)
        self.LAB_Sample_Comment = QtWidgets.QLabel(Form)
        self.LAB_Sample_Comment.setObjectName("LAB_Sample_Comment")
        self.verticalLayout.addWidget(self.LAB_Sample_Comment)
        self.TE_Sample_Comment = QtWidgets.QPlainTextEdit(Form)
        self.TE_Sample_Comment.setObjectName("TE_Sample_Comment")
        self.verticalLayout.addWidget(self.TE_Sample_Comment)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LAB_Sample_Name.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:700;\">*Sample Name</span></p></body></html>"))
        self.LAB_Sample_ID_2.setText(_translate("Form", "Sample ID (If you have)"))
        self.LAB_Sample_Comment.setText(_translate("Form", "Sample Comment"))
