# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/Widget_Equipment_Information.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.CMB_Method = QtWidgets.QComboBox(Form)
        self.CMB_Method.setObjectName("CMB_Method")
        self.CMB_Method.addItem("")
        self.CMB_Method.addItem("")
        self.CMB_Method.addItem("")
        self.CMB_Method.addItem("")
        self.CMB_Method.addItem("")
        self.verticalLayout.addWidget(self.CMB_Method)
        spacerItem = QtWidgets.QSpacerItem(17, 223, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:700;\">*Experiment Method</span></p></body></html>"))
        self.CMB_Method.setItemText(0, _translate("Form", "Powder diffraction"))
        self.CMB_Method.setItemText(1, _translate("Form", "Thin film"))
        self.CMB_Method.setItemText(2, _translate("Form", "2D diffraction map"))
        self.CMB_Method.setItemText(3, _translate("Form", "Inverse lattice map"))
        self.CMB_Method.setItemText(4, _translate("Form", "Other"))
